feat(users): Add script to change username
rivet-gg/opengb-registry pull request #74
Opened 2024-03-28 18:58 UTC by Blckbrry-Pi

2024-03-28 18:58 UTC, Blckbrry-Pi commented
* **#74** <a href="https://app.graphite.dev/github/pr/rivet-gg/opengb-registry/74?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Blckbrry-Pi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-28 21:44 UTC, MasterPtato requested changes

2024-03-28 21:44 UTC, MasterPtato commented on modules/users/scripts/update_username.ts
> +        }
This should be idempotent instead of throwing an error

2024-04-01 00:20 UTC, MasterPtato approved these changes

2024-04-16 18:38 UTC, NathanFlurry commented
Will probably repurpose this PR for an "update profile" script at some point once we figure out how we want to design user profiles (ie pfp, bio, etc), but closing for now. Would rather have missing functionality than signifiant breaking changes,

2024-04-16 18:38 UTC, closed without merging